name: ci-prod.yml

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

jobs:
  test:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: "Test using Playwright"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Placeholder"

  deploy:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Deploy to Cloudflare Pages (Production)
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Install NPM and build
        run: npm install && npm run build-prod

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages publish "dist/code-crow/browser" --project-name=cro-website

  create-tag:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Create Tag and Release
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get NPM version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Create a tag and release
        uses: ncipollo/release-action@v1.11.1
        with:
          tag: ${{ steps.package-version.outputs.current-version }}
          name: v${{ steps.package-version.outputs.current-version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
        continue-on-error: true
